-- 0001_core.sql
-- Source-agnostic health core.
--
-- Three raw shapes cover every source we expect:
--   interval  -> health.sessions    (app use, sleep, a run)
--   point     -> health.raw_events  (an unlock, a scale reading tap)
--   scalar    -> health.observations directly (weight, resting HR)
--
-- Everything Grafana reads lives in health.observations at a uniform grain.
-- Derived rows are rebuilt from raw by re-runnable functions, so changing a
-- bucketing rule is a backfill, not a data loss.

CREATE SCHEMA IF NOT EXISTS health;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_available_extensions WHERE name = 'timescaledb') THEN
    CREATE EXTENSION IF NOT EXISTS timescaledb;
  END IF;
END $$;

-- ---------------------------------------------------------------- registries

CREATE TABLE health.sources (
  id           smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key          text NOT NULL UNIQUE,
  display_name text NOT NULL,
  kind         text NOT NULL CHECK (kind IN ('device', 'service', 'manual')),
  created_at   timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE health.sources IS
  'One row per system that produces data: phone, ResMed, Strava, openScale.';

CREATE TABLE health.metrics (
  id           smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key          text NOT NULL UNIQUE,
  display_name text NOT NULL,
  unit         text NOT NULL,
  entity_kind  text,
  -- How this metric combines across time buckets. Screen time sums; a weight
  -- reading averages; a sleep score takes the last value of the day.
  agg          text NOT NULL DEFAULT 'sum' CHECK (agg IN ('sum', 'avg', 'last', 'max', 'min')),
  description  text
);

-- The thing an observation is *about*. An app, a shoe, a bed. Row 0 is the
-- sentinel "about me, not about a sub-thing" so entity_id can stay NOT NULL
-- and sit in a primary key.
CREATE TABLE health.entities (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind         text NOT NULL,
  key          text NOT NULL,
  display_name text NOT NULL,
  attrs        jsonb NOT NULL DEFAULT '{}',
  first_seen   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (kind, key)
);

INSERT INTO health.entities (id, kind, key, display_name)
VALUES (0, 'none', 'self', 'Self')
ON CONFLICT (id) DO NOTHING;

-- Runtime config that SQL needs to see. Chiefly the local timezone: "screen
-- time on Tuesday" means local midnight to local midnight, and that rule has
-- to live in exactly one place or every dashboard drifts.
CREATE TABLE health.config (
  key   text PRIMARY KEY,
  value text NOT NULL
);

INSERT INTO health.config (key, value) VALUES ('local_timezone', 'UTC')
ON CONFLICT (key) DO NOTHING;

CREATE FUNCTION health.local_tz() RETURNS text
  LANGUAGE sql STABLE AS
$$ SELECT value FROM health.config WHERE key = 'local_timezone' $$;

-- Local-midnight-aligned day for a UTC instant, returned as timestamptz so
-- Grafana plots it on a real time axis.
CREATE FUNCTION health.local_day(ts timestamptz) RETURNS timestamptz
  LANGUAGE sql STABLE AS
$$ SELECT date_trunc('day', $1 AT TIME ZONE health.local_tz()) AT TIME ZONE health.local_tz() $$;

CREATE FUNCTION health.local_hour_of_day(ts timestamptz) RETURNS integer
  LANGUAGE sql STABLE AS
$$ SELECT EXTRACT(hour FROM $1 AT TIME ZONE health.local_tz())::integer $$;

-- ------------------------------------------------------------- raw: interval

CREATE TABLE health.sessions (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id    smallint NOT NULL REFERENCES health.sources(id),
  session_type text NOT NULL,
  entity_id    integer NOT NULL DEFAULT 0 REFERENCES health.entities(id),
  started_at   timestamptz NOT NULL,
  ended_at     timestamptz NOT NULL,
  -- Deterministic per-source key. Re-uploading the same window must not
  -- duplicate rows; phones retry, and Strava restates activities.
  external_id  text NOT NULL,
  attrs        jsonb NOT NULL DEFAULT '{}',
  ingested_at  timestamptz NOT NULL DEFAULT now(),
  CHECK (ended_at >= started_at)
);

CREATE UNIQUE INDEX sessions_dedupe_idx
  ON health.sessions (source_id, session_type, external_id);
CREATE INDEX sessions_type_time_idx
  ON health.sessions (session_type, started_at DESC);
CREATE INDEX sessions_entity_time_idx
  ON health.sessions (entity_id, started_at DESC);

-- ---------------------------------------------------------------- raw: point

CREATE TABLE health.raw_events (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id   smallint NOT NULL REFERENCES health.sources(id),
  event_type  text NOT NULL,
  entity_id   integer NOT NULL DEFAULT 0 REFERENCES health.entities(id),
  ts          timestamptz NOT NULL,
  external_id text NOT NULL,
  attrs       jsonb NOT NULL DEFAULT '{}',
  ingested_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX raw_events_dedupe_idx
  ON health.raw_events (source_id, event_type, external_id);
CREATE INDEX raw_events_type_time_idx
  ON health.raw_events (event_type, ts DESC);

-- ------------------------------------------------------------------- derived

CREATE TABLE health.observations (
  ts        timestamptz NOT NULL,
  metric_id smallint NOT NULL REFERENCES health.metrics(id),
  source_id smallint NOT NULL REFERENCES health.sources(id),
  entity_id integer NOT NULL DEFAULT 0 REFERENCES health.entities(id),
  value     double precision NOT NULL,
  meta      jsonb NOT NULL DEFAULT '{}',
  -- source_id is in the key on purpose: two scales may both report a weight
  -- for the same instant, and we want to keep both rather than clobber.
  PRIMARY KEY (metric_id, source_id, entity_id, ts)
);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'timescaledb') THEN
    PERFORM create_hypertable(
      'health.observations', 'ts',
      chunk_time_interval => interval '30 days',
      if_not_exists       => true,
      migrate_data        => true
    );
  END IF;
END $$;

-- --------------------------------------------------------------- ingest audit

CREATE TABLE health.ingest_batches (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id     smallint NOT NULL REFERENCES health.sources(id),
  received_at   timestamptz NOT NULL DEFAULT now(),
  payload_sha256 text NOT NULL,
  payload_bytes integer NOT NULL,
  window_start  timestamptz,
  window_end    timestamptz,
  rows_written  integer NOT NULL DEFAULT 0,
  status        text NOT NULL DEFAULT 'ok',
  detail        jsonb NOT NULL DEFAULT '{}'
);

CREATE INDEX ingest_batches_source_time_idx
  ON health.ingest_batches (source_id, received_at DESC);

-- ------------------------------------------------------------------- helpers

CREATE FUNCTION health.upsert_entity(p_kind text, p_key text, p_display_name text)
RETURNS integer LANGUAGE plpgsql AS $$
DECLARE v_id integer;
BEGIN
  INSERT INTO health.entities (kind, key, display_name)
  VALUES (p_kind, p_key, p_display_name)
  ON CONFLICT (kind, key) DO UPDATE
    -- Keep the friendliest label we have ever seen; sources sometimes fall
    -- back to the bare package name when the launcher icon is unavailable.
    SET display_name = CASE
      WHEN EXCLUDED.display_name <> EXCLUDED.key THEN EXCLUDED.display_name
      ELSE health.entities.display_name
    END
  RETURNING id INTO v_id;
  RETURN v_id;
END $$;
